networks:
  app_network:
    driver: bridge

volumes:
  database_volume:
    driver: local

services:
  app:
    image: 'php:8.3-apache'
    restart: always
    ports:
      - "80"
    volumes:
      - .:/var/www/html
    networks:
      - app_network
  database:
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "database_volume:/var/lib/mysql"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: top-secret
      MYSQL_DATABASE: php_advanced
    networks:
      - app_network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database
    networks:
      - app_network